server:
  port: 9999
spring:
  application:
    name: easy-sweep
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.94.41.119:4406/easy-sweep?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: XpxproOt2008
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization.write-dates-as-timestamps: false
  redis:
    host: 47.94.41.119
    password: XpxproOt2008
  #配置邮箱
  mail:
    host: smtp.qq.com
    port: 465
    protocol: smtp
    username: 2271613696@qq.com
    nickname: easy-sweep
    password: wcbwrmvfumvmecbb
    default-encoding:  UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true #调试模式
    test-connection: false #启动项目时验证是否可以正确通信 默认为false
mybatis-plus:
  mapper-locations: classpath*:/mapper/sweep/*.xml
  typeAliasesPackage: com.xy.sweep.entity
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志

aliyun:
  oss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    accessKeyId: LTAI5tD9XCmJPcJPRTo6615R
    accessKeySecret: iGzS0ViWoCv4vAH2itQumtBzrUyS3B
    bucketName: xy-sweep